# Generated by Django 3.2 on 2021-04-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingo_server', '0002_auto_20210425_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSuggestion',
            fields=[
                ('word_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lingo_server.word')),
                ('approved', models.BooleanField()),
                ('rejected', models.BooleanField()),
            ],
            bases=('lingo_server.word',),
        ),
        migrations.AlterModelOptions(
            name='dictionaryversion',
            options={'verbose_name': 'Dictionary Version'},
        ),
    ]
