# Generated by Django 3.2 on 2021-04-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingo_server', '0003_auto_20210425_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordsuggestion',
            options={'verbose_name': 'Word Suggestion'},
        ),
        migrations.AlterField(
            model_name='wordsuggestion',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='wordsuggestion',
            name='rejected',
            field=models.BooleanField(null=True),
        ),
    ]
